### ISSUE TITLE
关于端元个数的设置

### ISSUE THREAD

**Issue by Scr-w** [neel-dey/robust-nmf#1]
请问关于端元个数是怎么设置的呢

**Comment by neel-dey** [comment]
Assuming that this translates to "how do you choose the number of endmembers" (I can't speak/read Mandarin, sorry): that question is really specific to the dataset and is best decided in collaboration with domain-experts. 

If it's truly blind/unknown, several automated heuristics to determine the number of components in a low-rank factorization or soft-clustering problem exist. E.g. HySime for hyperspectral imaging, minimum description length, automatic relevance determination if using bayesian methods, the elbow method, etc. Hope that helps.

**Comment by Scr-w** [comment]
I see. Thank you very much




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Neel ***@***.***&gt;; 
发送时间: 2021年4月17日(星期六) 凌晨2:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [neel-dey/robust-nmf] 关于端元个数的设置 (#1)






假设这转换为“如何选择最终成员的数量”（抱歉，我不会说/读普通话）：这个问题实际上是针对数据集的，最好与领域专家合作决定。

如果它是真正的盲/未知，一些自动启发式，以确定在低秩分解或软聚类问题的组件的数量存在。例如，用于高光谱成像的 Hy Sime ，最小描述长度，如果使用贝叶斯方法，肘法等的自动相关性确定。希望对你有帮助

—
您正在接收此消息，因为您编写了线程。
直接回复此邮件，在GitHub上查看，或取消订阅.
